# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum install -y pwgen
    # java
    yum install -y java-1.8.0-openjdk

    # elasticsearch
    rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
    echo "[elasticsearch-2.x]
name=Elasticsearch repository for 2.x packages
baseurl=https://packages.elastic.co/elasticsearch/2.x/centos
gpgcheck=1
gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1" > /etc/yum.repos.d/elasticsearch.repo
    yum install -y elasticsearch

    echo "cluster.name: graylogvg" >> /etc/elasticsearch/elasticsearch.yml

    systemctl start elasticsearch
    systemctl enable elasticsearch

    # mongodb
    echo "[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/mongodb.repo
    yum install -y mongodb-org-2.6.9 mongodb-org-server-2.6.9 mongodb-org-shell-2.6.9 mongodb-org-mongos-2.6.9 mongodb-org-tools-2.6.9
    chkconfig --add mongod
    systemctl start mongod
    systemctl enable mongod

    # graylog
    rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-2.2-repository_latest.rpm
    yum install -y graylog-server

    cp /etc/graylog/server/server.conf /etc/graylog/server/server.conf.orig
    SECRET=$(pwgen -s 96 1)
    PASSWORD=$(echo -n password | sha256sum | awk '{print $1}')
    IP=`/sbin/ifconfig enp0s8 | grep 'inet ' | cut -d" " -f10 | awk '{ print $1}'`
    sed -i -e 's/password_secret =.*/password_secret = '$SECRET'/' /etc/graylog/server/server.conf
    sed -i -e 's/root_password_sha2 =.*/root_password_sha2 = '$PASSWORD'/' /etc/graylog/server/server.conf
    sed -i -e 's/elasticsearch_shards = 4/elasticsearch_shards = 1/' /etc/graylog/server/server.conf
    sed -i -e 's/rest_listen_uri =.*//' /etc/graylog/server/server.conf
    echo "elasticsearch_cluster_name = graylogvg" >> /etc/graylog/server/server.conf
    echo "rest_listen_uri = http://$IP:9000/api/" >> /etc/graylog/server/server.conf
    echo "web_listen_uri = http://$IP:9000/" >> /etc/graylog/server/server.conf

    chkconfig --add graylog-server
    systemctl daemon-reload
    systemctl enable graylog-server.service
    systemctl start graylog-server.service
  SHELL
end
